name: quran_uz
description: Qur'oni karimning ma'nolar tarjimasi.
version: 2.2.0
homepage: https://github.com/MirrikhOpenSource/quran_uz

environment:
  sdk: '>=2.12.0 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies:
  equatable: ^2.0.5
